### ISSUE TITLE
Author of the Nuget

### ISSUE THREAD

**Issue by makma** [fingerprintjs/fingerprint-pro-server-api-dotnet-sdk#13]
The Nuget package says the author is Przemek. Since this is an official library, it should be Fingerprint.
![Screenshot 2023-03-13 at 18 39 49](https://user-images.githubusercontent.com/10922372/224783431-4c2056d0-249d-41e6-81f1-bf3d63d7b795.png)

**Comment by TheUnderScorer** [comment]
Resolved in #32
