### ISSUE TITLE
Get rid of Newtonsoft.Json and RestSharp

### ISSUE THREAD

**Issue by tcoreal** [fingerprintjs/fingerprint-pro-server-api-dotnet-sdk#34]
Newtonsoft.Json is obsolete and native System.Text.Json serialiser is way faster. The same is for RestSharp. And the nuget package will become lighter

**Comment by TheUnderScorer** [comment]
Hey @tcoreal,

Thanks for reporting this issue! 
We've put it in our backlog and we'll investigate possibility to do so in upcoming weeks.

**Comment by TheUnderScorer** [comment]
Hey @tcoreal!

This issue was fixed in [6.0.0](https://github.com/fingerprintjs/fingerprint-pro-server-api-dotnet-sdk/releases/tag/v6.0.0)
