### ISSUE TITLE
Headers in Configuration.DefaultHeader are not added to the HttpRequestMessage in ApiClient.CreateRequestMessage

### ISSUE THREAD

**Issue by joshsacks** [fingerprintjs/fingerprint-pro-server-api-dotnet-sdk#56]
This seems like an accidental oversight. We need to add headers to the outbound http request logging purposes.

We're adding them to the Configuration object with AddDefaultHeader(key, value). The DefaultHeader dictionary does not appear to be read from at all.

**Comment by TheUnderScorer** [comment]
Hey @joshsacks!

Thanks for reporting this issue, I'll look into it.

**Comment by joshsacks** [comment]
@TheUnderScorer It would also be super helpful if Configuration could have an optional property for HttpClient so we can pass in a client instance instead of ApiClient instantiating a new HttpClient() each time. (Of course if one not set, then ApiClient should instantiate a new one as it does now).

**Comment by joshsacks** [comment]
I'm happy to make this change (and resolve the original issue re DefaultHeader) as well if you'll entertain pull requests from the outside community.

**Comment by TheUnderScorer** [comment]
Sadly, for now we don't accept external contributions. However, I like the suggestion of having extra configuration option for `HttpClient` so I'll include it in the next release 🙂
